# Generated by Django 2.2.11 on 2020-03-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=13)),
                ('service', models.CharField(choices=[('홈페이지', '홈페이지'), ('쇼핑몰', '쇼핑몰'), ('웹앱', '웹앱'), ('챗봇', '챗봇'), ('IT솔루션', 'IT솔루션'), ('크롤링', '크롤링')], max_length=10)),
                ('url_type', models.CharField(blank=True, choices=[('벤치마킹', '벤치마킹'), ('홈페이지', '홈페이지')], max_length=10)),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
