# Generated by Django 2.2.11 on 2020-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='url_type',
        ),
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('홈페이지', '홈페이지'), ('챗봇', '챗봇'), ('웹앱', '웹앱'), ('크롤링', '크롤링'), ('IT솔루션', 'IT솔루션'), ('쇼핑몰', '쇼핑몰')], max_length=10),
        ),
    ]
