# Generated by Django 2.2.11 on 2020-03-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200326_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('크롤링', '크롤링'), ('쇼핑몰', '쇼핑몰'), ('웹앱', '웹앱'), ('홈페이지', '홈페이지'), ('챗봇', '챗봇'), ('IT솔루션', 'IT솔루션')], max_length=10),
        ),
    ]
