# Generated by Django 2.2.11 on 2020-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20200327_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('IT솔루션', 'IT솔루션'), ('챗봇', '챗봇'), ('쇼핑몰', '쇼핑몰'), ('웹앱', '웹앱'), ('크롤링', '크롤링'), ('홈페이지', '홈페이지')], max_length=10),
        ),
    ]
